# Generated by Django 2.0.7 on 2018-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
