# Generated by Django 2.0.7 on 2018-07-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapps', '0002_loanapp_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapp',
            name='app_url',
            field=models.URLField(default='NULL'),
        ),
    ]
